### ISSUE TITLE
Error regarding `Log` folder

### ISSUE THREAD

**Issue by Deepayan-Ghosh** [blavejr/OrganiseDesktop#42]
When I run `Clean.py` it gives me this error: 
```writeOB = open(path.dirname(os.getcwd()) + '/log/modifications.log', 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/home/deepayan/OrganiseDesktop/log/modifications.log
```
This occurs because the`log` folder does not exist. Did anyone else get this error?

**Comment by blavejr** [comment]
hmmm, hi @Deepayan-Ghosh I think it could be because no one has implemented ubuntu support.
I am really sorry I graduated got a job and I am still settling, it will be a couple of months before I am working on Organise again. but if you like you could fork it and try and add ubuntu support.
I think we already have Mac and windows support.
