### ISSUE TITLE
The option "undo" don't working

### ISSUE THREAD

**Issue by wescley** [blavejr/OrganiseDesktop#70]
Hi,

Good Nigth!

I tried to execute the program.
It cleaned my desktop, but when i tryied to execute the option "undo" nothing happening.

Holds

**Comment by blavejr** [comment]
Hey @wescley I havent looked at this code for a while but if you would like to try and solve this issue that would be highly appreciated.

**Comment by safderareepattamannil** [comment]
@blavejr I'm not sure I even see the undo script in OrganizeDesktop directory.

**Comment by KokoseiJ** [comment]
@blavejr This might be necropost, but I've found the issue. The problem is this line in the function undo:
`if environ.get('TEST_DIR') != '':`
I guess this value is None or something like that, which is not same as empty string, I guess?
You can fix this by changing that line to:
`if environ.get('TEST_DIR'):`.
I've tested, now it works well.

**Comment by KokoseiJ** [comment]
Fixed in PR #79. I'll close this issue.
